import "../styles/globals.css";
import Navbar from "../components/Navbar";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <title>Conor Doherty | Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo-icon.ico" />
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
